# Generated by Django 3.0.6 on 2021-12-15 15:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Photo of user', null=True, upload_to='images/User', verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Başlık Bilgisi Burada Girilir.', max_length=100, null=True, verbose_name='Başlık Giriniz.')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='İçerik Burada Girilir.', max_length=10000, null=True, verbose_name='İçerik Giriniz.')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, help_text='Photo of news', null=True, upload_to='images/News', verbose_name='image')),
                ('image_is_fit_to_screen', models.BooleanField(default=False, help_text='Resimin çerçeveye sığdırılması için işaretleyiniz, orjinal boyutunda kullanmak için işaretlemeyiniz.', verbose_name='Resmi çerçeveye sığdır.')),
                ('show_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, help_text='Haberin canlı ortamda yayınlanıp yayınlanmaması için seçim yapılır.', verbose_name='Yayınlansın')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_user', to='binance.Profile')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LikeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like_news', to='binance.News')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Beğenilen Haberler',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Please enter comment', max_length=10000, null=True, verbose_name='Enter Comment')),
                ('creator_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_created_by', to='binance.Profile')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='binance.News')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Başlık Bilgisi Burada Girilir.', max_length=30, null=True, verbose_name='Başlık Giriniz.')),
                ('content', models.TextField(blank=True, help_text='İçerik Detaylarını İsterseniz Bu Alandan Girilir.', max_length=10000, null=True, verbose_name='İçerik Detaylarını İsterseniz Bu Alandan Girebilirsiniz.')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, help_text='kapak foto', null=True, upload_to='images/Announcement', verbose_name='resim')),
                ('like_count', models.IntegerField(default=0)),
                ('show_count', models.IntegerField(default=0)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announce_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
