# Generated by Django 3.0.6 on 2021-12-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Coin adı burada girilir.', max_length=100, null=True, verbose_name='Coin adını giriniz.')),
                ('trustRate', models.IntegerField(default=2)),
                ('openToBuy', models.BooleanField(default=True, help_text='Alıma açık olup olmamasına burada karar verilir.', verbose_name='Alıma açık mı ?')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Coin',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchangePair', models.TextField(help_text='Trade çifti.', max_length=100, null=True, verbose_name='Trade çifti.')),
                ('count', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade', to='binance.Coin')),
            ],
            options={
                'verbose_name_plural': 'Trade',
                'ordering': ['id'],
            },
        ),
    ]
