# Generated by Django 3.0.6 on 2021-12-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0004_auto_20211226_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxLimitAsUsdt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Preferences',
                'ordering': ['id'],
            },
        ),
    ]
