# Generated by Django 3.0.6 on 2021-12-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0005_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='maxLimitAsUsdt',
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxLimitForRobotAsUsdt',
            field=models.IntegerField(default=0, verbose_name='Robotun kullanacağı maksimum Usdt tutarı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxLimitTotal',
            field=models.IntegerField(default=0, verbose_name='Manuel ve robotun kullanacağı toplam maksimum Usdt tutarı'),
        ),
    ]
