# Generated by Django 3.0.6 on 2021-12-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0006_auto_20211226_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='maxLimitTotal',
        ),
        migrations.AddField(
            model_name='preferences',
            name='usedUsdtForRobotAsUsdt',
            field=models.FloatField(default=0, verbose_name='Robotun kullandığı Usdt tutarı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='maxLimitForRobotAsUsdt',
            field=models.FloatField(default=0, verbose_name='Robotun kullanacağı maksimum Usdt tutarı'),
        ),
    ]
