# Generated by Django 3.0.6 on 2021-12-28 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0007_auto_20211226_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preferences',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.AddField(
            model_name='preferences',
            name='generalTradingExchangePair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferences_generalTradingExchangePair', to='binance.Coin'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isBuyingModeActive',
            field=models.BooleanField(default=False, help_text='Alış modu açık mı? ', verbose_name='Alış modu açık mı? '),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isEmaControlActiveForBuying',
            field=models.BooleanField(default=True, help_text='Alım yaparken Ema kontrolü aktif mi ?', verbose_name='Alım yaparken Ema kontrolü aktif mi ?'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isEmaControlActiveForSelling',
            field=models.BooleanField(default=False, help_text='EMA düşükteyse birer kademe pozitif durumdakilerden satış yapılsın mı? ', verbose_name='EMA düşükteyse birer kademe pozitif durumdakilerden satış yapılsın mı? '),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isSellingModeActive',
            field=models.BooleanField(default=False, help_text='Satış modu açık mı? ', verbose_name='Satış modu açık mı? '),
        ),
        migrations.AddField(
            model_name='trade',
            name='buyedByRobot',
            field=models.BooleanField(default=True, help_text='Robot tarafından mı alındı  ?', verbose_name='Robot tarafından mı alındı ?'),
        ),
    ]
