# Generated by Django 3.0.6 on 2021-12-28 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0008_auto_20211228_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='generalTradingExchangePair',
            field=models.ForeignKey(help_text='Alış satışlarda kullanılacak dolayısı ile biriktirilecek para birimi seçiniz.  ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferences_generalTradingExchangePair', to='binance.Coin', verbose_name='Alış satışlarda kullanılacak dolayısı ile biriktirilecek para birimi seçiniz.  '),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isBuyingModeActive',
            field=models.BooleanField(default=True, help_text='Alış modu açık mı? ', verbose_name='Alış modu açık mı? '),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isSellingModeActive',
            field=models.BooleanField(default=True, help_text='Satış modu açık mı? ', verbose_name='Satış modu açık mı? '),
        ),
    ]
