# Generated by Django 3.0.6 on 2021-12-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0009_auto_20211228_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='generalTradingExchangePair',
        ),
        migrations.AddField(
            model_name='preferences',
            name='coinTargetToCollect',
            field=models.ForeignKey(help_text='Biriktirilmesi istenen para birimini seçiniz.  ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferences_coinTargetToCollect', to='binance.Coin', verbose_name='Biriktirilmesi istenen para birimini seçiniz.  '),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isSellingOneStepIfDoesntPassEMAControlModeActive',
            field=models.BooleanField(default=True, help_text='EMA kontrolünden geçmediyse artıda olan tradelerin yarısını satsın mı ? ', verbose_name='EMA kontrolünden geçmediyse artıda olan tradelerin yarısını satsın mı ? '),
        ),
        migrations.AddField(
            model_name='trade',
            name='howManyTimesSold',
            field=models.IntegerField(default=0),
        ),
    ]
