# Generated by Django 3.0.6 on 2022-01-05 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0010_auto_20211229_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='isEmaControlActiveForSelling',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='usedUsdtForRobotAsUsdt',
        ),
        migrations.AddField(
            model_name='preferences',
            name='isControlForPanicMode',
            field=models.BooleanField(default=True, help_text='Bu özellik açıldıysa btc son 24 saatte %10 ve üzerinde düşüş yaparsa ve Ema aşağıda olursa panik modu devreye girer tüm pozisyonları kapatıp usdt ye dönülür .  ', verbose_name='Bu özellik açıldıysa btc son 24 saatte %10 ve üzerinde düşüş yaparsa ve Ema aşağıda olursa panik modu devreye girer tüm pozisyonları kapatıp usdt ye dönülür .  '),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isPanicModeActive',
            field=models.BooleanField(default=True, help_text='Panik modu açık mı? ', verbose_name='Panik modu açık mı? '),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxOpenTradeCountForSameCoin',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='trade',
            name='firstCount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='firstPriceAgainstBtc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='lastSellDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='transactionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
