# Generated by Django 3.0.6 on 2022-01-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0011_auto_20220105_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='preferredCompareCoinName',
            field=models.TextField(default='BTC', help_text='Karşılaştırılacak coin adı burada girilir.', max_length=100, verbose_name='Karşılaştırılacak coin adını giriniz.'),
        ),
    ]
