# Generated by Django 3.0.6 on 2022-01-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0012_coin_preferredcomparecoinname'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='isExistFromPanicModeAutomaticallyActive',
            field=models.BooleanField(default=True, help_text='Panik modundan otomatik çıkış açık mı? ', verbose_name='Panik modundan otomatik çıkış açık mı? '),
        ),
    ]
