# Generated by Django 3.0.6 on 2022-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0013_preferences_isexistfrompanicmodeautomaticallyactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='cooldownForNewBuyFromSameCoin',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='preferences',
            name='cooldownForNewSellFromSameCoin',
            field=models.IntegerField(default=3),
        ),
    ]
