# Generated by Django 3.0.6 on 2022-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0015_auto_20220108_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='maxRSI',
            field=models.IntegerField(default=80, help_text='Max RSI (80)', verbose_name='Max RSI (80)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='midRSI',
            field=models.IntegerField(default=50, help_text='Mid RSI (50)', verbose_name='Mid RSI (50)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='minRSI',
            field=models.IntegerField(default=20, help_text='Min RSI (20)', verbose_name='Min RSI (20)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='williamR',
            field=models.IntegerField(default=-50, help_text='WilliamR (50)', verbose_name='WilliamR (50)'),
        ),
    ]
