# Generated by Django 3.0.6 on 2022-01-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0016_auto_20220108_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='williamR',
            field=models.IntegerField(default=-50, help_text='WilliamR (-50)', verbose_name='WilliamR (-50)'),
        ),
    ]
