# Generated by Django 3.0.6 on 2022-01-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0017_auto_20220108_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='isControlForPanicMode',
            field=models.BooleanField(default=True, help_text='Bu özellik açıldıysa btc son 24 saatte %10 ve üzerinde düşüş yaparsa ve Ema aşağıda olursa (Ema 20 günlük ortalama altında ise) panik modu devreye girer tüm pozisyonları kapatıp usdt ye dönülür .  ', verbose_name='Panik moduna otomatik giriş için kontrol açık mı?'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isEmaControlActiveForBuying',
            field=models.BooleanField(default=True, help_text='Alım yaparken Ema kontrolü aktif mi ?(Varsayılan olarak BTC nin 20 günlük ortalama üzerinde olması şartı aranır)', verbose_name='Alım yaparken Ema kontrolü aktif mi ? (Varsayılan olarak BTC nin 20 günlük ortalama üzerinde olması şartı aranır))'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isExistFromPanicModeAutomaticallyActive',
            field=models.BooleanField(default=True, help_text='Bu seçenek seçili ve Ema kontrolü pozitif kapanırsa panik modundan otomatik olarak çıkış yapılır ', verbose_name='Panik modundan otomatik çıkış açık mı? '),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isPanicModeActive',
            field=models.BooleanField(default=True, help_text='Panik modu şuan açık mı? ', verbose_name='Panik modu şuan açık mı? '),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isSellingOneStepIfDoesntPassEMAControlModeActive',
            field=models.BooleanField(default=True, help_text='EMA kontrolünden geçmediyse artıda olan tradelerin yarısını satsın mı ? (Varsayılan olarak BTC nin 20 günlük ortalamanın altında kalması durumunda satış yapar) ', verbose_name='EMA kontrolünden geçmediyse artıda olan tradelerin yarısını satsın mı ? (Varsayılan olarak BTC nin 20 günlük ortalamanın altında kalması durumunda satış yapar) '),
        ),
    ]
