# Generated by Django 3.0.6 on 2022-01-10 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0018_auto_20220109_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robotUsing', models.FloatField(default=0)),
                ('freeUsdt', models.FloatField(default=0)),
                ('manuelUsing', models.FloatField(default=0)),
                ('transactionDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
