# Generated by Django 3.0.6 on 2022-01-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0019_totalbalancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='temp_totalCurrentPrice',
            field=models.FloatField(default=0),
        ),
    ]
