# Generated by Django 3.0.6 on 2022-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0021_processlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForBuying',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForSelling',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='trade',
            name='temp_currentPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='temp_differenceToBTCPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='temp_differenceTotalAsUSDT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='temp_profitLossPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='temp_profitLossTimes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='temp_ratioToTotalPercentage',
            field=models.FloatField(default=0),
        ),
    ]
