# Generated by Django 3.0.6 on 2022-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0022_auto_20220117_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='cooldownForNewBuyFromSameCoin',
            field=models.IntegerField(default=3, help_text='Yeni alım yapmak için minimum x gün geçmeli'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='cooldownForNewSellFromSameCoin',
            field=models.IntegerField(default=3, help_text='Yeni satış yapmak için minimum x gün geçmeli'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='maxOpenTradeCountForSameCoin',
            field=models.IntegerField(default=2, help_text='Aynı coinden en fazla kaç adet açık trade bulundurabilir ?'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForBuying',
            field=models.IntegerField(default=5, help_text='Alış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSelling',
            field=models.IntegerField(default=5, help_text='Satış yapmak için beklenen min fark'),
        ),
    ]
