# Generated by Django 3.0.6 on 2022-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0023_auto_20220117_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='isPassiveInEarn',
            field=models.BooleanField(default=False, help_text='Kazan bölümünde mi ? (Eğer öyle ise satış yapılmaz sadece görüntülenir.)', verbose_name='Kazan bölümünde mi ? (Eğer öyle ise satış yapılmaz sadece görüntülenir.)'),
        ),
    ]
