# Generated by Django 3.0.6 on 2022-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0024_trade_ispassiveinearn'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='differentExchangeName',
            field=models.TextField(help_text='Farklı Borsanın Adı', max_length=1000, null=True, verbose_name='Farklı Borsanın Adı'),
        ),
        migrations.AddField(
            model_name='trade',
            name='isDifferentExchange',
            field=models.BooleanField(default=False, help_text='Farklı Borsada Mı (Borsada bulunan tutar USDT olarak girilir)?', verbose_name='Farklı Borsada Mı(Borsada bulunan tutar USDT olarak girilir) ?'),
        ),
    ]
