# Generated by Django 3.0.6 on 2022-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0025_auto_20220118_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='differentExchangeName',
            field=models.TextField(default='Binance', help_text='Farklı Borsanın Adı', max_length=1000, null=True, verbose_name='Farklı Borsanın Adı'),
        ),
    ]
