# Generated by Django 3.0.6 on 2022-01-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0027_preferences_commontotalstartmoneyasusdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='commonTotalStartMoneyAsTL',
            field=models.FloatField(default=0),
        ),
    ]
