# Generated by Django 3.0.6 on 2022-01-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0028_preferences_commontotalstartmoneyastl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='indicatorResults',
            field=models.TextField(blank=True, default='', help_text='Son çalıştığında indicatorlerin güncel durumları yazılır', max_length=1000, null=True, verbose_name='Son çalıştığında indicatorlerin güncel durumları yazılır'),
        ),
    ]
