# Generated by Django 3.0.6 on 2022-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0031_auto_20220122_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='isFlexWhileBuying',
            field=models.BooleanField(default=True, help_text='Robot kendine ayrılan tutarın %25 inden az kullanıyorsa Alım yapılırken buysignal daki minRsi değeri 10 yukarı (varsayılan 20 ise, 30kullanılır) çekilir. Eğer %25 i geçmiş ve %50 den az ise minRsi değeri 5 yukarı(25 yani) çekilir. Robot limitinin %50 sini geçtiyse varsayılan minRsi değeri kullanılır ', verbose_name='Alım yaparken esnesin mi?'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isEmaControlActiveForBuying',
            field=models.BooleanField(default=True, help_text='Alım yaparken Ema kontrolü aktif mi ?(Varsayılan olarak BTC nin 20 günlük ortalama üzerinde olması şartı aranır)', verbose_name='Ema kontrolü açık mı? (Alım yaparken)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isPanicModeActive',
            field=models.BooleanField(default=True, help_text='Panik modu şuan açık mı?  (Panik modu açıldığında Alış ve satış modları kapalı ya çekilir ve kapatıldığında diğerleri açılır)', verbose_name='Panik modu şuan açık mı?'),
        ),
    ]
