# Generated by Django 3.0.6 on 2022-01-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0034_auto_20220123_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='addBudgetToRobotWhenTargetToTopComes_AddBudget',
            field=models.FloatField(default=0, help_text='Btc üst hedef aksiyonu tetiklendiğinde eklenecek miktar', verbose_name='Bütçe üst hedefte eklenecek tutar'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='addBudgetToRobotWhenTargetToTopComes_BtcTargetArea',
            field=models.FloatField(default=0, help_text='Aksiyonun tetiklenmesi için Btc nin üzerine çıkması gereken değer', verbose_name='Bütçe btc üst hedefi'),
        ),
    ]
