# Generated by Django 3.0.6 on 2022-01-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0036_preferences_test_totalbalancehistory_test_trade_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences_test',
            name='coinTargetToCollect',
        ),
        migrations.DeleteModel(
            name='TotalBalanceHistory_Test',
        ),
        migrations.RemoveField(
            model_name='trade_test',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='trade_test',
            name='exchangePair',
        ),
        migrations.DeleteModel(
            name='Preferences_Test',
        ),
        migrations.DeleteModel(
            name='Trade_Test',
        ),
    ]
