# Generated by Django 3.0.6 on 2022-01-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0037_auto_20220124_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbalancehistory',
            name='btc',
            field=models.FloatField(default=0, help_text='Btc son durum', verbose_name='Btc'),
        ),
    ]
