# Generated by Django 3.0.6 on 2022-02-01 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0039_preferences_lastrobotworkingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processType', models.TextField(help_text='Buy Sell', max_length=5, null=True, verbose_name='İşlem Tipi')),
                ('coinName', models.TextField(help_text='Coin adı burada girilir.', max_length=100, null=True, verbose_name='Coin adı')),
                ('exchangeCoinName', models.TextField(help_text='Coin adı burada girilir.', max_length=100, null=True, verbose_name='Coin adı')),
                ('count', models.FloatField(default=0, help_text='Elde kalan mevcut adet . Satışlardan sonra güncellenir.', verbose_name='Elde kalan mevcut adet')),
                ('price', models.FloatField(default=0, help_text='Alış fiyatı Usdt olarak', verbose_name='Alış fiyatı Usdt')),
                ('buyedByRobot', models.BooleanField(default=True, help_text='Robot tarafından mı alındı?', verbose_name='Robot mu aldı?')),
                ('transactionDate', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Alımın yapıldığı tarih otomatik olarak alım yapıldığında girilir', verbose_name='Alış Tarihi')),
            ],
        ),
    ]
