# Generated by Django 3.0.6 on 2022-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0042_auto_20220201_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='isBuyAutomaticallyAfterPanicMode',
            field=models.BooleanField(default=True, help_text='Panik modundan otomatik çıkış açıkken panik modundan çıkış aşamasında bu alanı kontrol eder ve işaretli ise otomatik olarak birer kademe alır. Alım yaptıktan sonra bu alanı false yapar.)', verbose_name='Panik modundan çıkışta otomatik coin al. (aldıktan sonra false yapılacaktır.)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lastSellDate',
            field=models.DateTimeField(blank=True, help_text='Satış yapıldığında tarih girilir', null=True, verbose_name='Son satış tarihi'),
        ),
    ]
