# Generated by Django 3.0.6 on 2022-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0044_tradelog_profitlosspercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='buyedByRobot',
            field=models.BooleanField(default=True, help_text='Robot tarafından mı alındı?', verbose_name='Robot mu aldı?'),
        ),
    ]
