# Generated by Django 3.0.6 on 2022-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0045_tradelog_buyedbyrobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='buyedByRobot',
            field=models.BooleanField(default=False, help_text='Robot tarafından mı alındı?', verbose_name='Robot mu aldı?'),
        ),
    ]
