# Generated by Django 3.0.6 on 2022-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0046_auto_20220209_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='buyedByRobot',
            field=models.BooleanField(default=False, help_text='Robot mu işlemi yaptı?', verbose_name='Robot mu işlemi yaptı?'),
        ),
    ]
