# Generated by Django 3.0.6 on 2022-02-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0047_auto_20220212_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='isFlexWhileBuying',
            field=models.BooleanField(default=True, help_text='Robot kullanılan : <25 => minRSI:+10 || <50 => minRSI:+5 & maxRSI+5 || >80 => minRSI:-2 , >90 => minRSI:-5 || >65 => maxRSI-5 || >85 => maxRSI-10 ', verbose_name='Alım yaparken esnesin mi?'),
        ),
    ]
