# Generated by Django 3.0.6 on 2022-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0050_auto_20220215_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='temp_emaLowWarningStartDate',
            field=models.DateTimeField(blank=True, help_text='Ema nın ortalama altına ilk düştüğü tarih.(Eğer ema üzerine çıkılırsa bu tarhi boşaltılır.)', null=True, verbose_name='Ema uyarı başlama tarihi'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isFlexWhileBuying',
            field=models.BooleanField(default=True, help_text='Robot kullanılan : <25 => minRSI:+10 || <50 => minRSI:+6 & maxRSI+5 || <65 => minRSI:+4 || <75 => minRSI:+2 || >90 => minRSI:-2 , >95 => minRSI:-5 || >70 => maxRSI-5 || >85 => maxRSI-10 || minRSI normal değer : 65 ile 90 arası ve maxRSI normal değer : 50 ile 70 arası', verbose_name='Alım yaparken esnesin mi?'),
        ),
    ]
