# Generated by Django 3.0.6 on 2022-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0051_auto_20220220_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maxLimitForBTCLongAsUsdt',
            field=models.FloatField(default=0, help_text='Kaldıraç robotun kullanacağı maksimum usdt tutarı', verbose_name='Kaldıraç bütçe'),
        ),
    ]
