# Generated by Django 3.0.6 on 2022-02-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0052_preferences_maxlimitforbtclongasusdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='maxLimitForBTCLongAsUsdt',
        ),
        migrations.AddField(
            model_name='preferences',
            name='cooldownForNewBuyFromSameCoinBaseForLong',
            field=models.IntegerField(default=1, help_text='Yeni alım yapmak için minimum (x * eldeki adet) kadar gün geçmeli', verbose_name='Margin Long için taban cooldown gün sayisi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isMarginRobotActive',
            field=models.BooleanField(default=False, help_text='Ema üzerindeyken long açıp, ema altındayken short açan marginli robot çalışıyor mu?', verbose_name='Margin robotu açık mı?'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxLimitForMarginAsUsdt',
            field=models.FloatField(default=50, help_text='Margin Long robotun kullanacağı maksimum usdt tutarı', verbose_name='Margin Long Bütçe'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxOpenTradeCountForMargin',
            field=models.IntegerField(default=5, help_text='Margin Long işlem için aynı coin adet limiti', verbose_name='Margin Long işlem için aynı coin adet limiti'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxRSIForLong',
            field=models.IntegerField(default=65, help_text='Margin Long için Max RSI (Varsayılan değeri 80)', verbose_name='Margin Long Max RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxRSIForShort',
            field=models.IntegerField(default=70, help_text='Margin Short için Max RSI (Varsayılan değeri 80)', verbose_name='Margin Short Max RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='minRSIForLong',
            field=models.IntegerField(default=25, help_text='Margin Long için Min RSI (Varsayılan değeri 20)', verbose_name='Margin Long Min RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='minRSIForShort',
            field=models.IntegerField(default=30, help_text='Margin Short için Min RSI (Varsayılan değeri 20)', verbose_name='Margin Short Min RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopPercentageForSellingForLong',
            field=models.IntegerField(default=10, help_text='Margin Long için zarar kes yapılacak yüzdelik oran', verbose_name='Margin Long için zarar kes yapılacak yüzdelik oran'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForSellingForLong',
            field=models.IntegerField(default=2, help_text='Margin Long için Satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='Margin Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='usedLimitForMarginAsUsdt',
            field=models.FloatField(default=0, help_text='Margin Long robotun kullandığı toplam usdt tutarı', verbose_name='Margin Long Bütçeden Kullanılan'),
        ),
        migrations.AddField(
            model_name='trade',
            name='isMargin',
            field=models.BooleanField(default=False, help_text='Kaldıraçlı mı alındı?', verbose_name='Kaldıraçlı mı alındı?'),
        ),
    ]
