# Generated by Django 3.0.6 on 2022-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0054_auto_20220224_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='isControlEmaForMarginTrades',
            field=models.BooleanField(default=True, help_text='Margin tradelerde EMAyı kontrol etsin mi?', verbose_name='Margin tradelerde EMAyı kontrol etsin mi?'),
        ),
    ]
