# Generated by Django 3.0.6 on 2022-02-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0055_preferences_iscontrolemaformargintrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='isMargin',
            field=models.BooleanField(default=False, help_text='Kardıraçlı coin mi ?', verbose_name='Kardıraçlı coin mi?'),
        ),
    ]
