# Generated by Django 3.0.6 on 2022-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0056_coin_ismargin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='maxRSIForLong',
            field=models.IntegerField(default=65, help_text='Margin Long için Max RSI (Varsayılan değeri 65)', verbose_name='Margin Long Max RSI'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='maxRSIForShort',
            field=models.IntegerField(default=70, help_text='Margin Short için Max RSI (Varsayılan değeri 70)', verbose_name='Margin Short Max RSI'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='minRSIForLong',
            field=models.IntegerField(default=20, help_text='Margin Long için Min RSI (Varsayılan değeri 20)', verbose_name='Margin Long Min RSI'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='minRSIForShort',
            field=models.IntegerField(default=30, help_text='Margin Short için Min RSI (Varsayılan değeri 30)', verbose_name='Margin Short Min RSI'),
        ),
    ]
