# Generated by Django 3.0.6 on 2022-02-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0057_auto_20220225_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='isControlEmaForSellingPreviousMarginTrades',
            field=models.BooleanField(default=False, help_text='EMA terse döndüğünde diğer margin tradeleri zararda da olsa satsın mı?', verbose_name='EMA terse döndüğünde diğer margin tradeleri zararda da olsa satsın mı?'),
        ),
    ]
