# Generated by Django 3.0.6 on 2022-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0058_preferences_iscontrolemaforsellingpreviousmargintrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='isControlEmaForMarginTrades',
            field=models.BooleanField(default=True, help_text='Margin tradelerde EMAyı kontrol ederek Long veya Short tan sadece bir türde alım yapar', verbose_name='Margin tradelerde EMAyı kontrol ederek Long veya Short tan sadece bir türde alım yapar'),
        ),
    ]
