# Generated by Django 3.0.6 on 2022-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0059_auto_20220225_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='lastMarginRobotWorkingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son margin robotun çalışma tarihi'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='lastRobotWorkingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son robotun çalışma tarihi'),
        ),
    ]
