# Generated by Django 3.0.6 on 2022-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0060_auto_20220227_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='cooldownForNewBuyFromSameCoinBaseForLong',
        ),
        migrations.AddField(
            model_name='preferences',
            name='cooldownAsHoursForNewBuyFromSameCoinBaseForMargin',
            field=models.IntegerField(default=1, help_text='Yeni alım yapmak için minimum (x * eldeki adet) kadar saat geçmeli', verbose_name='Margin Long ve Short için taban cooldown saat sayisi'),
        ),
    ]
