# Generated by Django 3.0.6 on 2022-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0063_auto_20220228_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='marginResultHistoryAsUsdt',
            field=models.FloatField(default=0, help_text='Margin geçmişten bu yana alım satımlardan yapılan kar zarar durumu', verbose_name='Margin geçmişten bu yana alım satımlardan yapılan kar zarar durumu'),
        ),
    ]
