# Generated by Django 3.0.6 on 2022-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0064_preferences_marginresulthistoryasusdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbalancehistory',
            name='marginResultHistory',
            field=models.FloatField(default=0, help_text='Margin tradelerin toplamdaki kar zarar olarak son durum', verbose_name='Margin Trade Kar/Zarar'),
        ),
    ]
