# Generated by Django 3.0.6 on 2022-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0066_auto_20220301_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='robotResultHistoryAsUsdt',
            field=models.FloatField(default=0, help_text='Robot geçmişten bu yana alım satımlardan yapılan kar zarar durumu', verbose_name='Robot geçmişten bu yana alım satımlardan yapılan kar zarar durumu'),
        ),
    ]
