# Generated by Django 3.0.6 on 2022-03-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0067_preferences_robotresulthistoryasusdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbalancehistory',
            name='robotResultHistory',
            field=models.FloatField(default=0, help_text='Robot tradelerin toplamdaki kar zarar olarak son durum', verbose_name='Robot Trade Kar/Zarar'),
        ),
    ]
