# Generated by Django 3.0.6 on 2022-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0070_auto_20220309_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='temp_isRobotWorkingNow',
            field=models.BooleanField(default=False, verbose_name='Bu Alan Manuel Değiştirilmez ! (Robot Şuan Çalışıyor Mu?)'),
        ),
    ]
