# Generated by Django 3.0.6 on 2022-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0072_auto_20220318_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maxLimitForRobot15mAsUsdt',
            field=models.FloatField(default=0, help_text='RSI_15m Robotun kullanacağı maksimum usdt tutarı', verbose_name='Robot RSI_15m bütçe'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot15mNegativeSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m zararına satış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot15mPositiveSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m karlı satış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot15mTotalBuyCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m toplam alış sayısı'),
        ),
        migrations.AddField(
            model_name='trade',
            name='strategy',
            field=models.TextField(blank=True, default='', help_text='Örnek : Margin_RSI_15m , RSI_15m , RSI_4h', max_length=100, null=True, verbose_name='Alış ve Satış Stratejisi'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isFlexWhileBuying',
            field=models.BooleanField(default=True, help_text='Robot kullanılan : <25 => minRSI:+10 || <50 => minRSI:+6 & maxRSI+5 || <65 => minRSI:+4 || <75 => minRSI:+2 || >90 => minRSI:-2 , >95 => minRSI:-5 || >70 => maxRSI-5 || >85 => maxRSI-10 || minRSI normal değer : 65 ile 90 arası ve maxRSI normal değer : 50 ile 70 arası', verbose_name='Satış yaparken esnesin mi?(Alım esnemesi iptal edildi)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='marginRobotNegativeSellCount',
            field=models.IntegerField(default=0, verbose_name='Margin_RSI_15m robot zararına satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='marginRobotPositiveSellCount',
            field=models.IntegerField(default=0, verbose_name='Margin_RSI_15m robot karlı satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='marginRobotTotalBuyCount',
            field=models.IntegerField(default=0, verbose_name='Margin_RSI_15m robot toplam alış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robotNegativeSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_4h zararına satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robotPositiveSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_4h karlı satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robotTotalBuyCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_4h toplam alış sayısı'),
        ),
    ]
