# Generated by Django 3.0.6 on 2022-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0075_auto_20220319_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.TextField(blank=True, default='', help_text='Örnek : Margin_RSI_15m , RSI_15m , RSI_4h , Specified_Priority_Purchases , Manuel_Webpage_Action , Manuel_Entered', max_length=100, null=True, verbose_name='Alış ve Satış Stratejisi'),
        ),
    ]
