# Generated by Django 3.0.6 on 2022-03-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0076_auto_20220319_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbalancehistory',
            name='robot15mResultHistory',
            field=models.FloatField(default=0, help_text='Robot RSI_15m tradelerin toplamdaki kar zarar olarak son durum', verbose_name='Robot Trade Kar/Zarar'),
        ),
    ]
