# Generated by Django 3.0.6 on 2022-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0078_auto_20220320_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='stopPercentageForSellingForRobot15m',
            field=models.IntegerField(default=-10, help_text='Margin_RSI_15m ve RSI_15m Long için zarar kes yapılacak yüzdelik oran', verbose_name='RSI_15m Long için zarar kes yapılacak yüzdelik oran'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForSellingForRobot15m',
            field=models.IntegerField(default=2, help_text='Margin_RSI_15m ve RSI_15m Long veya Short için Satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='RSI_15m Long veya Short için Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMargin',
            field=models.IntegerField(default=-10, verbose_name='Margin_RSI_15m Long için zarar kes yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSellingForMargin',
            field=models.IntegerField(default=2, verbose_name='Margin_RSI_15m Long veya Short için Satış yapmak için beklenen min fark'),
        ),
    ]
