# Generated by Django 3.0.6 on 2022-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0082_auto_20220321_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMargin',
            field=models.IntegerField(default=-10, verbose_name='Margin_RSI_15m Long için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForRobot15m',
            field=models.IntegerField(default=-10, help_text='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran', verbose_name='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
    ]
