# Generated by Django 3.0.6 on 2022-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0084_auto_20220325_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='temp_startForMarginAsUsdt',
            field=models.FloatField(default=500, verbose_name='Robot Margin başlangıç bütçesi (Değiştirilmez)'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='temp_startForRobot15mAsUsdt',
            field=models.FloatField(default=500, verbose_name='Robot RSI_15m başlangıç bütçesi (Değiştirilmez)'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='temp_startForRobotAsUsdt',
            field=models.FloatField(default=500, verbose_name='Robot RSI_4h başlangıç bütçesi (Değiştirilmez)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMargin',
            field=models.IntegerField(default=-10, verbose_name='Margin_RSI_15m Long ve Short için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exchangeCoinName',
            field=models.TextField(max_length=100, null=True, verbose_name='Fiyat Çifti'),
        ),
    ]
