# Generated by Django 3.0.6 on 2022-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0086_auto_20220329_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='strategy',
            field=models.TextField(blank=True, default='', help_text='Örnek : Margin_RSI_15m , RSI_15m , RSI_4h , Specified_Priority_Purchases , Manuel_Webpage_Action , Manuel_Entered', max_length=100, null=True, verbose_name='Alış ve Satış Stratejisi'),
        ),
    ]
