# Generated by Django 3.0.6 on 2022-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0087_tradelog_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='passedDaysToSell',
            field=models.IntegerField(default=0, verbose_name='Kaç günde satıldı?'),
        ),
    ]
