# Generated by Django 3.0.6 on 2022-04-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0088_tradelog_passeddaystosell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='targetPercentageForSellingForMargin',
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForLongSellingForMargin',
            field=models.IntegerField(default=1, verbose_name='Margin_RSI_15m Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForShortSellingForMargin',
            field=models.IntegerField(default=1, verbose_name='Margin_RSI_15m Short için Satış yapmak için beklenen min fark'),
        ),
    ]
