# Generated by Django 3.0.6 on 2022-04-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0089_auto_20220408_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='isControlEmaForMarginTrades',
        ),
    ]
