# Generated by Django 3.0.6 on 2022-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0090_remove_preferences_iscontrolemaformargintrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='limitPercentageForSellingForMargin',
            field=models.IntegerField(default=5, verbose_name='Margin_RSI_15m Long ve Short için beklenen max kar yüzdelik oran'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='limitPercentageForSellingForRobot15m',
            field=models.IntegerField(default=5, help_text='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran', verbose_name='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
    ]
