# Generated by Django 3.0.6 on 2022-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0091_auto_20220412_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='limitPercentageForSellingForMargin',
            field=models.IntegerField(default=5, verbose_name='Margin_RSI_15m Long ve Short için kar satışı yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='limitPercentageForSellingForRobot15m',
            field=models.IntegerField(default=5, verbose_name='RSI_15m için kar satışı yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMargin',
            field=models.IntegerField(default=-5, verbose_name='Margin_RSI_15m Long ve Short için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
    ]
