# Generated by Django 3.0.6 on 2022-04-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0092_auto_20220414_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='stopBuyingDateFor15m',
            field=models.DateTimeField(blank=True, help_text='Robot15m peş peşe 3 tane zararına satış yapıldığı zaman bu tarih alanını doldur ve 12 saat boyunca başka alım yapma. 12 saat sonra bu alanı boşaltıp tekrar alımlara devam et.', null=True, verbose_name='Robot15m alış durduruşunun başlama tarihi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopBuyingDateFor4h',
            field=models.DateTimeField(blank=True, help_text='Robot4h peş peşe 3 tane zararına satış yapıldığı zaman bu tarih alanını doldur ve 12 saat boyunca başka alım yapma. 12 saat sonra bu alanı boşaltıp tekrar alımlara devam et.', null=True, verbose_name='Robot4h alış durduruşunun başlama tarihi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopBuyingDateForMargin',
            field=models.DateTimeField(blank=True, help_text='Margin peş peşe 3 tane zararına satış yapıldığı zaman bu tarih alanını doldur ve 12 saat boyunca başka alım yapma. 12 saat sonra bu alanı boşaltıp tekrar alımlara devam et.', null=True, verbose_name='Margin alış durduruşunun başlama tarihi'),
        ),
    ]
