# Generated by Django 3.0.6 on 2022-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0094_auto_20220418_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='isMarginRobotLongActive',
            field=models.BooleanField(default=True, help_text='Margin Robot açık olduğunda bu seçenekte açık ise Ema üzerindeyken long açan marginli robot çalışıyor mu?', verbose_name='Margin robotu long alım açık mı?'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isMarginRobotShortActive',
            field=models.BooleanField(default=True, help_text='Margin Robot açık olduğunda bu seçenekte açık ise Ema altındayken short açan marginli robot çalışıyor mu?', verbose_name='Margin robotu short alım açık mı?'),
        ),
    ]
