# Generated by Django 3.0.6 on 2022-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0095_auto_20220425_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='stopLossTriggerStartPercentage',
            field=models.FloatField(default=4, help_text='Örneğin %4 kar ettikten sonra tetiklenir', verbose_name='StopLoss başlama yüzdesi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopLossTriggerStopPercentage',
            field=models.FloatField(default=1, help_text='Örneğin tetiklendikten sonra %1 kaybettiğinde çalışır', verbose_name='StopLoss kaybı durdurma yüzdesi'),
        ),
        migrations.AddField(
            model_name='trade',
            name='stopLossLastTriggeredPercentage',
            field=models.FloatField(default=0, help_text='StopLoss tetiklendikten sonraki en yüksek kar seviyesi yüzdesi', verbose_name='StopLoss tetiklenme yüzdesi'),
        ),
    ]
