# Generated by Django 3.0.6 on 2022-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0096_auto_20220721_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='temp_draftUsdtDiffDateAction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Takip Usdt Resetlenme Zamanı'),
        ),
    ]
