# Generated by Django 3.0.6 on 2022-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0099_auto_20221019_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbalancehistory',
            name='marginBTCResultHistory',
            field=models.FloatField(default=0, help_text='MarginBTC tradelerin toplamdaki kar zarar olarak son durum', verbose_name='MarginBTC Trade Kar/Zarar'),
        ),
    ]
