# Generated by Django 3.0.6 on 2022-10-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0101_auto_20221024_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSelling',
            field=models.FloatField(default=5, help_text='Satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='Satış yapmak için beklenen min fark'),
        ),
    ]
