# Generated by Django 3.0.6 on 2022-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0102_auto_20221025_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='cooldownForNewBuyFromSameCoin',
            field=models.IntegerField(default=1, help_text='Yeni alım yapmak için minimum x gün geçmeli', verbose_name='Aynı coinin alımı için geçmesi gereken gün'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='cooldownForNewSellFromSameCoin',
            field=models.IntegerField(default=1, help_text='Yeni satış yapmak için minimum x gün geçmeli', verbose_name='Aynı coinin satışı için geçmesi gereken gün'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='givenLimitHoursForRobot15mThenTryToSell',
            field=models.FloatField(default=2, verbose_name='Verilen saat kadar sat sinyali beklenecek, satılamazsa sürenin sonuna gelindiğinde trade 0.1 kar ve üzerindeyse hemen satılacak'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='givenLimitHoursForRobotMarginThenTryToSell',
            field=models.FloatField(default=2, verbose_name='Verilen saat kadar sat sinyali beklenecek, satılamazsa sürenin sonuna gelindiğinde trade 0.1 kar ve üzerindeyse hemen satılacak'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='limitPercentageForSellingForMargin',
            field=models.FloatField(default=3, verbose_name='Margin_RSI_15m Long ve Short için kar satışı yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='limitPercentageForSellingForRobot15m',
            field=models.FloatField(default=3, verbose_name='RSI_15m için kar satışı yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMargin',
            field=models.FloatField(default=-0.5, verbose_name='Margin_RSI_15m Long ve Short için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMarginBTC',
            field=models.FloatField(default=-0.5, verbose_name='Margin_RSI_15m Long ve Short için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForRobot15m',
            field=models.FloatField(default=-0.5, help_text='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran', verbose_name='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForBuying',
            field=models.FloatField(default=3, help_text='Aynı coinden alım yapılırken yeni fiyatın önceki alım fiyatından minimum yüzde x kadar ucuz olması gerekir', verbose_name='Alış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForLongSellingForMargin',
            field=models.FloatField(default=0.5, verbose_name='Margin_RSI_15m Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForLongSellingForMarginBTC',
            field=models.FloatField(default=0.5, verbose_name='MarginBTC Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSelling',
            field=models.FloatField(default=0.5, help_text='Satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSellingForRobot15m',
            field=models.FloatField(default=0.5, help_text='RSI_15m için satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='RSI_15m için Satış yapmak için beklenen min kar farkı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForShortSellingForMargin',
            field=models.FloatField(default=0.5, verbose_name='Margin_RSI_15m Short için Satış yapmak için beklenen min fark'),
        ),
    ]
