# Generated by Django 3.0.6 on 2022-10-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0103_auto_20221025_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='stopLossTriggerStopPercentageMarginBTC',
            field=models.FloatField(default=0.75, help_text='Örneğin tetiklendikten sonra %1 kaybettiğinde çalışır', verbose_name='MarginBTC StopLoss kaybı durdurma yüzdesi'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMargin',
            field=models.FloatField(default=-0.75, verbose_name='Margin_RSI_15m Long ve Short için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMarginBTC',
            field=models.FloatField(default=-0.75, verbose_name='Margin_RSI_15m Long ve Short için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForRobot15m',
            field=models.FloatField(default=-0.75, help_text='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran', verbose_name='RSI_15m için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForLongSellingForMargin',
            field=models.FloatField(default=0.75, verbose_name='Margin_RSI_15m Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForLongSellingForMarginBTC',
            field=models.FloatField(default=0.75, verbose_name='MarginBTC Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSelling',
            field=models.FloatField(default=0.75, help_text='Satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSellingForRobot15m',
            field=models.FloatField(default=0.75, help_text='RSI_15m için satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='RSI_15m için Satış yapmak için beklenen min kar farkı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForShortSellingForMargin',
            field=models.FloatField(default=0.75, verbose_name='Margin_RSI_15m Short için Satış yapmak için beklenen min fark'),
        ),
    ]
