# Generated by Django 3.0.6 on 2022-11-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0104_auto_20221025_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='givenLimitHoursForRobot15mThenTryToSell',
            field=models.FloatField(default=2, verbose_name='robot15m Verilen saat kadar sat sinyali beklenecek, satılamazsa sürenin sonuna gelindiğinde trade 0.1 kar ve üzerindeyse hemen satılacak'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='givenLimitHoursForRobotMarginThenTryToSell',
            field=models.FloatField(default=2, verbose_name='robotmargin Verilen saat kadar sat sinyali beklenecek, satılamazsa sürenin sonuna gelindiğinde trade 0.1 kar ve üzerindeyse hemen satılacak'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForLongSellingForMargin',
            field=models.FloatField(default=0.75, verbose_name='Margin Long için Satış yapmak için beklenen min fark'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForShortSellingForMargin',
            field=models.FloatField(default=0.75, verbose_name='Margin Short için Satış yapmak için beklenen min fark'),
        ),
    ]
