# Generated by Django 3.0.6 on 2022-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0106_preferences_waithoursafternegativesell'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maxRSIForLongForBTC',
            field=models.IntegerField(default=45, help_text='Margin_BTC için Max RSI (Varsayılan değeri 65)', verbose_name='Margin_BTC Max RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='minRSIForLongForBTC',
            field=models.IntegerField(default=25, help_text='Margin_BTC için Min RSI (Varsayılan değeri 20)', verbose_name='Margin_BTC Min RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForSellingForRobotBTC',
            field=models.FloatField(default=0.7, help_text='Margin_BTC için satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='Margin_BTC için Satış yapmak için beklenen min kar farkı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='stopPercentageForSellingForMarginBTC',
            field=models.FloatField(default=-1, verbose_name='Margin_BTC için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
    ]
