# Generated by Django 3.0.6 on 2022-11-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0107_auto_20221104_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='isUsableForRSI1h',
            field=models.BooleanField(default=False, verbose_name='RSI1h mantığıyla daha yavaş al/sat hedefleyen algoritma için uygun coin mi?'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='cooldownAsHoursForNewBuyFromSameCoinBaseFor1h',
            field=models.IntegerField(default=6, help_text='RSI_1h için yeni alım yapmak için minimum (x * eldeki adet) kadar saat geçmeli', verbose_name='RSI_1h için taban cooldown saat sayisi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isControlEmaForSellingPreviousRobot1hTrades',
            field=models.BooleanField(default=True, verbose_name='EMA nın %5 altındaysa elinde RSI_15m_Slow robot ile alınmış coinler varsa sat'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isRobot1hActive',
            field=models.BooleanField(default=False, help_text='Ema üzerindeyken alım ve satım yapan, ema nın %5 altındayken stop olan RSI_15m_Slow robot çalışıyor mu?', verbose_name='RSI_15m_Slow robotu açık mı?'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='lastRobot1hWorkingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son RSI_15m robotun çalışma tarihi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='lossLimitForRobot1h',
            field=models.FloatField(default=-100, help_text='Robotun bu zarar altına geldiğinde komple çalışmayacak. İstenirse sonradan arttırılabilir.', verbose_name='Robot RSI_1h zarar limiti'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxLimitForRobot1hAsUsdt',
            field=models.FloatField(default=400, help_text='RSI_15m_Slow Robotun kullanacağı maksimum usdt tutarı', verbose_name='Robot RSI_15m_Slow bütçe'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxOpenTradeCountForRobot1h',
            field=models.IntegerField(default=2, help_text='RSI_1h işlem için aynı coin adet limiti', verbose_name='RSI_1h işlem için aynı coin adet limiti'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxRSIForRobot1h',
            field=models.IntegerField(default=60, help_text='RSI_15m_Slow için Max RSI (Varsayılan değeri 65)', verbose_name='RSI_15m_Slow Max RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='minRSIForRobot1h',
            field=models.IntegerField(default=30, help_text='RSI_15m_Slow için Min RSI (Varsayılan değeri 20)', verbose_name='RSI_15m_Slow Min RSI'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot1hNegativeSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_1h zararına satış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot1hPositiveSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_1h karlı satış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot1hResultHistoryAsUsdt',
            field=models.FloatField(default=0, help_text='Robot RSI_1h geçmişten bu yana alım satımlardan yapılan kar zarar durumu', verbose_name='Robot RSI_1h geçmişten bu yana alım satımlardan yapılan kar zarar durumu'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot1hTotalBuyCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_1h toplam alış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopBuyingDateFor1h',
            field=models.DateTimeField(blank=True, help_text='Robot1h peş peşe 3 tane zararına satış yapıldığı zaman bu tarih alanını doldur ve 12 saat boyunca başka alım yapma. 12 saat sonra bu alanı boşaltıp tekrar alımlara devam et.', null=True, verbose_name='Robot1h alış durduruşunun başlama tarihi (Değiştirilmez)'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopPercentageForSellingForRobot1h',
            field=models.FloatField(default=-10, help_text='RSI_1h için zarar kes(stop) yapılacak yüzdelik oran', verbose_name='RSI_1h için zarar kes(stop) yapılacak yüzdelik oran'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='targetPercentageForSellingForRobot1h',
            field=models.FloatField(default=10, help_text='RSI_15m_Slow için satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='RSI_15m_Slow için Satış yapmak için beklenen min kar farkı'),
        ),
    ]
