# Generated by Django 3.0.6 on 2022-11-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0108_auto_20221104_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='givenLimitHoursForRobot1hThenTryToSell',
            field=models.FloatField(default=72, verbose_name='robot1h Verilen saat kadar sat sinyali beklenecek, satılamazsa sürenin sonuna gelindiğinde trade 0.1 kar ve üzerindeyse hemen satılacak'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isControlEmaForSellingPreviousRobot1hTrades',
            field=models.BooleanField(default=True, verbose_name='EMA nın %5 altındaysa elinde RSI_1h robot ile alınmış coinler varsa sat'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='isRobot1hActive',
            field=models.BooleanField(default=False, help_text='Ema üzerindeyken alım ve satım yapan, ema nın %5 altındayken stop olan RSI_1h robot çalışıyor mu?', verbose_name='RSI_1h robotu açık mı?'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='lastRobot1hWorkingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son RSI_1h robotun çalışma tarihi'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='maxLimitForRobot1hAsUsdt',
            field=models.FloatField(default=400, help_text='RSI_1h Robotun kullanacağı maksimum usdt tutarı', verbose_name='Robot RSI_1h bütçe'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='maxRSIForRobot1h',
            field=models.IntegerField(default=60, help_text='RSI_1h için Max RSI (Varsayılan değeri 65)', verbose_name='RSI_1h Max RSI'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='minRSIForRobot1h',
            field=models.IntegerField(default=30, help_text='RSI_1h için Min RSI (Varsayılan değeri 20)', verbose_name='RSI_1h Min RSI'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='targetPercentageForSellingForRobot1h',
            field=models.FloatField(default=10, help_text='RSI_1h için satış yapılırken minimum yüzde x kadar kar edilmiş olması gerekir', verbose_name='RSI_1h için Satış yapmak için beklenen min kar farkı'),
        ),
    ]
