# Generated by Django 3.0.6 on 2022-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0110_auto_20221105_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='temp_startForRobot15mSlowAsUsdt',
            field=models.FloatField(default=500, verbose_name='Robot RSI_15m_Slow başlangıç bütçesi (Değiştirilmez)'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='temp_startForRobot1hAsUsdt',
            field=models.FloatField(default=500, verbose_name='Robot RSI_1h başlangıç bütçesi (Değiştirilmez)'),
        ),
    ]
