# Generated by Django 3.0.6 on 2022-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0111_auto_20221105_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maxRSIFor1hSlow',
            field=models.IntegerField(default=55, help_text='RSI_15m_Slow için Max RSI 1h için (Varsayılan değeri 65)', verbose_name='RSI_15m_Slow Max RSI 1h için'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='minRSIFor1hSlow',
            field=models.IntegerField(default=25, help_text='RSI_15m_Slow için Min RSI 1h için (Varsayılan değeri 20)', verbose_name='RSI_15m_Slow Min RSI 1h için'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='minRSIFor15mSlow',
            field=models.IntegerField(default=15, help_text='RSI_15m_Slow için Min RSI (Varsayılan değeri 20)', verbose_name='RSI_15m_Slow Min RSI'),
        ),
    ]
