# Generated by Django 3.0.6 on 2022-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0112_auto_20221107_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='stopBuyingDateForMarginBTC',
            field=models.DateTimeField(blank=True, help_text='MarginBTC 1 tane zararına satış yapıldığı zaman bu tarih alanını doldur ve 6 saat boyunca başka alım yapma. 6 saat sonra bu alanı boşaltıp tekrar alımlara devam et.', null=True, verbose_name='MarginBTC alış durduruşunun başlama tarihi (Değiştirilmez)'),
        ),
    ]
