# Generated by Django 3.0.6 on 2022-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0113_auto_20221108_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='moveRSI15mComeBackRSIValueForBtc',
            field=models.IntegerField(default=0, verbose_name='RSI15m için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSI15mComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, verbose_name='RSI15m için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSI15mSlowComeBackRSIValueForBtc',
            field=models.IntegerField(default=0, verbose_name='RSI15mSlow için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSI15mSlowComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, verbose_name='RSI15mSlow için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSI1hComeBackRSIValueForBtc',
            field=models.IntegerField(default=0, verbose_name='RSI15m için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSI1hComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, verbose_name='RSI15m için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSIMarginBtcComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, verbose_name='RSIMarginBtc için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='coin',
            name='moveRSIMarginLongComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, verbose_name='RSIMarginLong için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='moveRSIComeBackPercentage',
            field=models.IntegerField(default=5, verbose_name='RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.'),
        ),
    ]
