# Generated by Django 3.0.6 on 2022-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0114_auto_20221206_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='isUsableForRSI15m',
            field=models.BooleanField(default=False, help_text='RSI15 için uygun coin mi?', verbose_name='RSI15 için uygun'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='isUsableForRSI1h',
            field=models.BooleanField(default=False, help_text='RSI1h mantığıyla daha yavaş al/sat hedefleyen algoritma için uygun coin mi?', verbose_name='RSI1h için uygun'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSI15mComeBackRSIValueForBtc',
            field=models.IntegerField(default=0, help_text='RSI15m için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSI15mBTC'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSI15mComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, help_text='RSI15m için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSI15mUSDT'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSI15mSlowComeBackRSIValueForBtc',
            field=models.IntegerField(default=0, help_text='RSI15mSlow için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSI15mSlowBTC'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSI15mSlowComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, help_text='RSI15mSlow için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSI15mSlowUSDT'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSI1hComeBackRSIValueForBtc',
            field=models.IntegerField(default=0, help_text='RSI1h için RSI ın btc karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSI1hBTC'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSI1hComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, help_text='RSI1h için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSI1hUSDT'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSIMarginBtcComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, help_text='RSIMarginBtc için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSIMarginBTC'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='moveRSIMarginLongComeBackRSIValueForUsdt',
            field=models.IntegerField(default=0, help_text='RSIMarginLong için RSI ın usdt karşısındaki değeri düştükten sonra x değer kadar yükseldiğinde satın alma siyali gelir.', verbose_name='Kontrol RSIMarginLongUSDT'),
        ),
    ]
