# Generated by Django 3.0.6 on 2023-01-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0115_auto_20221207_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last15RSIBTC',
            field=models.IntegerField(default=0, help_text='Son 15m rsi değeri BTC', verbose_name='Son 15m rsi değeri BTC'),
        ),
        migrations.AddField(
            model_name='coin',
            name='last15RSIUSDT',
            field=models.IntegerField(default=0, help_text='Son 15m rsi değeri USDT', verbose_name='Son 15m rsi değeri USDT'),
        ),
    ]
