# Generated by Django 3.0.6 on 2023-01-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0116_auto_20230107_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='isControlEmaForSellingPreviousRobot15mWITHRealMarginTrades',
            field=models.BooleanField(default=True, verbose_name='EMA nın %5 altındaysa elinde RSI_15m_WITHRealMargin robot ile alınmış coinler varsa sat'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isRobot15mWithRealMarginActive',
            field=models.BooleanField(default=False, help_text='Ema üzerindeyken alım ve satım yapan, ema nın %5 altındayken stop olan RSI_15m_WITHRealMargin robot çalışıyor mu?', verbose_name='RSI_15m_WITHRealMargin robotu açık mı?'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='lastRobot15mWITHRealMarginWorkingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son RSI_15m_WITHRealMargin robotun çalışma tarihi'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='lossLimitForRobot15mWITHRealMargin',
            field=models.FloatField(default=-100, help_text='Robotun bu zarar altına geldiğinde komple çalışmayacak. İstenirse sonradan arttırılabilir.', verbose_name='Robot RSI_15m_WITHRealMargin zarar limiti'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maxLimitForRobot15mWithRealMarginAsUsdt',
            field=models.FloatField(default=200, help_text='RSI_15m_WITHRealMargin Robotun kullanacağı maksimum usdt tutarı', verbose_name='Robot RSI_15m_WITHRealMargin bütçe'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot15mWITHRealMarginResultHistoryAsUsdt',
            field=models.FloatField(default=0, help_text='Robot RSI_15m geçmişten bu yana alım satımlardan yapılan kar zarar durumu', verbose_name='Robot RSI_15m geçmişten bu yana alım satımlardan yapılan kar zarar durumu'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stopBuyingDateFor15mWITHRealMargin',
            field=models.DateTimeField(blank=True, help_text='Robot15mWihRealMargin peş peşe 3 tane zararına satış yapıldığı zaman bu tarih alanını doldur ve 12 saat boyunca başka alım yapma. 12 saat sonra bu alanı boşaltıp tekrar alımlara devam et.', null=True, verbose_name='Robot15mWihRealMargin alış durduruşunun başlama tarihi (Değiştirilmez)'),
        ),
    ]
