# Generated by Django 3.0.6 on 2023-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0117_auto_20230123_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='robot15mWITHRealMarginNegativeSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m zararına satış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot15mWITHRealMarginPositiveSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m karlı satış sayısı'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='robot15mWITHRealMarginTotalBuyCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m toplam alış sayısı'),
        ),
    ]
