# Generated by Django 3.0.6 on 2023-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0118_auto_20230123_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='temp_startForRobot15mWITHRealMarginAsUsdt',
            field=models.FloatField(default=500, verbose_name='Robot RSI_15m_WITHRealMargin başlangıç bütçesi (Değiştirilmez)'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robot15mWITHRealMarginNegativeSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m_WithRealMargin zararına satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robot15mWITHRealMarginPositiveSellCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m_WithRealMargin karlı satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robot15mWITHRealMarginTotalBuyCount',
            field=models.IntegerField(default=0, verbose_name='Robot RSI_15m_WithRealMargin toplam alış sayısı'),
        ),
    ]
