# Generated by Django 3.0.6 on 2023-01-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0120_auto_20230123_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='robot15mWITHRealMarginPositiveSellCount',
            field=models.IntegerField(default=1, verbose_name='Robot RSI_15m_WITHRealMargin karlı satış sayısı'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='robot15mWITHRealMarginTotalBuyCount',
            field=models.IntegerField(default=1, verbose_name='Robot RSI_15m_WITHRealMargin toplam alış sayısı'),
        ),
    ]
