# Generated by Django 3.0.6 on 2023-01-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0121_auto_20230123_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maxRSIFor15mWITHRealMargin',
            field=models.IntegerField(default=40, help_text='Max RSI  WITH Real Margin (Varsayılan değeri 80)', verbose_name='Max RSI WITH Real Margin'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='minRSIFor15mWITHRealMargin',
            field=models.IntegerField(default=20, help_text='Min RSI  WITH Real Margin (Varsayılan değeri 20)', verbose_name='Min RSI WITH Real Margin'),
        ),
    ]
